"""Generate .cursor/rules from armature.yaml architecture config."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_cursor_rules(config: ArmatureConfig) -> Path:
    """Generate .cursor/rules with architecture and quality rules."""
    root = Path.cwd()
    cursor_dir = root / ".cursor"
    cursor_dir.mkdir(exist_ok=True)
    rules_path = cursor_dir / "rules"

    lines = [
        "# Armature -- Architectural constraints for Cursor",
        "# Generated by: armature hooks --cursor",
        "",
    ]

    # Architecture boundaries
    if config.architecture.enabled and config.architecture.boundaries:
        lines.append("## Layer Boundaries")
        lines.append("")
        for rule in config.architecture.boundaries:
            lines.append(f"- Code in `{rule.from_layer}` layer MUST NOT import from: {', '.join(rule.to_layers)}")
        lines.append("")
        if config.architecture.allowed_shared:
            lines.append("## Shared Infrastructure (always importable)")
            for shared in config.architecture.allowed_shared:
                lines.append(f"- `{shared}`")
            lines.append("")

    # Conformance rules
    if config.architecture.conformance:
        lines.append("## Class Conformance")
        for rule in config.architecture.conformance:
            lines.append(f"- Classes matching `*{rule.pattern}*` must inherit from `{rule.base_class}`")
            if rule.required_methods:
                lines.append(f"  Required methods: {', '.join(rule.required_methods)}")
        lines.append("")

    # Quality gates
    if config.quality.enabled:
        lines.append("## Quality Requirements")
        lines.append(f"- Run `armature check` before committing")
        lines.append(f"- Quality gates: draft={config.quality.gates.get('draft', 0.7)}, "
                     f"review_ready={config.quality.gates.get('review_ready', 0.85)}, "
                     f"merge_ready={config.quality.gates.get('merge_ready', 0.95)}")
        lines.append("")

    rules_path.write_text("\n".join(lines), encoding="utf-8")
    return rules_path
