"""Generate .github/workflows/armature.yml CI workflow."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_github_actions(config: ArmatureConfig) -> Path:
    """Generate GitHub Actions workflow for Armature checks."""
    root = Path.cwd()
    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    path = workflows_dir / "armature.yml"

    python_version = "3.11"
    workflow = f"""# Armature Harness Engineering CI
# Generated by: armature hooks --github-actions
# Marketplace: https://github.com/marketplace/actions/armature-quality-gates

name: Armature

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  checks: write          # required for GitHub Checks API annotations
  contents: read

jobs:
  armature-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"

      - name: Install dependencies
        run: |
          pip install armature-harness[{config.project.language}]
          pip install -e ".[dev]" 2>/dev/null || true

      - name: Armature Check
        id: armature-check
        run: |
          set +e
          OUTPUT=$(armature check --json 2>&1)
          EXIT_CODE=$?
          echo "$OUTPUT"
          echo "json_output<<EOF" >> "$GITHUB_OUTPUT"
          echo "$OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          exit $EXIT_CODE

      - name: Post GitHub Checks annotations
        if: always() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
          GITHUB_REPOSITORY: ${{{{ github.repository }}}}
          GITHUB_SHA: ${{{{ github.sha }}}}
        run: |
          python - <<'PYEOF'
          import os, json
          from armature.integrations.github_checks import post_check_run
          from armature._internal.types import CheckResult
          raw = os.environ.get("ARMATURE_JSON_OUTPUT", "[]")
          try:
              data = json.loads(raw)
              results = [CheckResult(
                  name=r["name"], passed=r["passed"],
                  violation_count=r.get("violations", 0),
                  details=r.get("details", ""),
                  score=r.get("score", 1.0),
                  weight=r.get("weight", 25),
              ) for r in data]
          except Exception:
              results = []
          post_check_run(results)
          PYEOF

      - name: Armature GC
        run: armature gc --json
        if: github.event_name == 'pull_request'

      - name: Generate HTML Report
        if: always()
        run: |
          mkdir -p .armature
          armature report --html --output .armature/report.html || true

      - name: Upload Quality Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: armature-quality-report
          path: .armature/report.html
          if-no-files-found: warn
"""

    path.write_text(workflow, encoding="utf-8")
    return path

