"""Generate .windsurfrules from armature.yaml."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_windsurf_rules(config: ArmatureConfig) -> Path:
    """Generate Windsurf rules from architecture config."""
    root = Path.cwd()
    path = root / ".windsurfrules"

    lines = [
        "# Armature -- Architectural constraints for Windsurf",
        "# Generated by: armature hooks --windsurf",
        "",
        "Run `armature check` to verify code quality before committing.",
        "Run `armature heal --failures lint` to auto-fix lint issues.",
        "",
    ]

    if config.architecture.enabled:
        lines.append("Architecture boundaries:")
        for rule in config.architecture.boundaries:
            lines.append(f"- {rule.from_layer} must not import from: {', '.join(rule.to_layers)}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
