"""Generate .github/copilot-instructions.md from armature.yaml."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_copilot_instructions(config: ArmatureConfig) -> Path:
    """Generate GitHub Copilot instructions from architecture config."""
    root = Path.cwd()
    github_dir = root / ".github"
    github_dir.mkdir(exist_ok=True)
    path = github_dir / "copilot-instructions.md"

    lines = [
        "# Copilot Instructions",
        "",
        "Generated by [Armature](https://github.com/armature-dev/armature) -- "
        "harness engineering for AI coding agents.",
        "",
    ]

    if config.architecture.enabled:
        lines.append("## Architecture")
        lines.append("")
        for rule in config.architecture.boundaries:
            lines.append(f"- `{rule.from_layer}` layer must not import from: {', '.join(rule.to_layers)}")
        lines.append("")

    if config.quality.enabled:
        lines.append("## Quality")
        lines.append("")
        lines.append("- Run `armature check` to verify code quality")
        lines.append("- Run `armature heal --failures lint` to auto-fix lint issues")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
