"""Generate .github/workflows/armature.yml CI workflow."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_github_actions(config: ArmatureConfig) -> Path:
    """Generate GitHub Actions workflow for Armature checks."""
    root = Path.cwd()
    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    path = workflows_dir / "armature.yml"

    python_version = "3.11"
    workflow = f"""# Armature Harness Engineering CI
# Generated by: armature hooks --github-actions

name: Armature

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  armature-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "{python_version}"

      - name: Install dependencies
        run: |
          pip install armature[{config.project.language}]
          pip install -e ".[dev]" 2>/dev/null || true

      - name: Armature Check
        run: armature check --json

      - name: Armature GC
        run: armature gc --json
        if: github.event_name == 'pull_request'
"""

    path.write_text(workflow, encoding="utf-8")
    return path
