"""Generate .pre-commit-config.yaml for Armature hooks."""

from __future__ import annotations

from pathlib import Path

from armature.config.schema import ArmatureConfig


def generate_pre_commit(config: ArmatureConfig) -> Path:
    """Generate pre-commit config with Armature hooks."""
    root = Path.cwd()
    path = root / ".pre-commit-config.yaml"

    content = """# Armature pre-commit hooks
# Generated by: armature hooks --pre-commit

repos:
  - repo: local
    hooks:
      - id: armature-check
        name: Armature Quality Check
        entry: armature check
        language: system
        pass_filenames: false
        always_run: true
"""

    path.write_text(content, encoding="utf-8")
    return path
